const ROUTER = {
  LOGIN: "/dang-nhap",
  USER: "/nguoi-dung",
  ACCOUNT: "/tai-khoan",
  ORDER: "/don-hang",
  ORDER_DETAIL: "chi-tiet-don-hang",
  CREATE_ORDER: "tao-don-hang",
  SUPPLIER: "nha-cung-cap",
  CONFIG: "/cau-hinh",
  CHANGE_PASSWORD: "doi-mat-khau",
};

const STRING = {
  login: "Đăng nhập",
  logout: "Đăng xuất",
  forgotPassword: "Quên mật khẩu",
  password: "Mật khẩu",
  confirmPassword: "Xác nhận mật khẩu",
  resetPassword: "Reset password",
  changePassword: "Đổi mật khẩu",
  numericalOrder: "STT",
  addNew: "Thêm mới",
  add: "Thêm",
  cancel: "Hủy",
  save: "Lưu",
  phoneNumber: "Số điện thoại",
  address: "Địa chỉ",
  createdDate: "Ngày tạo",
  lastUpdatedDate: "Ngày cập nhật cuối",
  supplier: "Nhà cung cấp",
  export: "Export",
  search: "Tìm kiếm",
  delete: "Xóa",
  deleteSearching: "Xóa tìm kiếm",
  creator: "Người tạo",
  updatePerson: "Người cập nhật",
  representative: "Người đại diện",
  construction: "Công trình",
  orderCode: "Mã đơn hàng",
  contractCode: "Mã hợp đồng",
  dueDate: "Thời hạn hoàn công",
  status: "Trạng thái",
  totalMoney: "Tổng tiền",
  vnd: "VNĐ",
  supplierCode: "Mã nhà cung cấp",
  supplierName: "Tên nhà cung cấp",
  email: "Email",
  tax: "Mã số thuế",
  contactAddress: "Địa chỉ liên hệ",
  officeAddress: "Địa chỉ trụ sở",
  fullName: "Họ tên",
  staffName: "Tên nhân viên",
  account: "Tài khoản",
  addAccount: "Thêm tài khoản",
  deleteAccount: "Xóa tài khoản",
  editAccount: "Sửa tài khoản",
  config: "Cấu hình",
  supplier: "Nhà cung cấp",
  addSupplier: "Thêm nhà cung cấp",
  editSupplier: "Sửa nhà cung cấp",
  order: "Đơn hàng",
  orderDetail: "Chi tiết đơn hàng",
  createOrder: "Tạo đơn hàng",
  editOrder: "Sửa đơn hàng",
  complete: "Hoàn thành",
  orderInfo: "Thông tin đơn hàng",
  constructionName: "Tên công trình",
  warrantyPeriod: "Thời hạn bảo hành",
  percentFinePerDay: "Quá hạn phạt mỗi ngày",
  document: "Tài liệu",
  purchaseContent: "Nội dung mua hàng",
  constructType: "Loại công trình",
  productType: "Loại sản phẩm",
  taxMoney: "Số tiền trước thuế",
  import: "Nhập khẩu",
  payment: "Thanh toán",
  paymentDate: "Ngày thanh toán",
  moneyUnit: "Đơn vị tiền",
  year: "Năm",
  paymentMethod: "Phương thức thanh toán",
  paymentClause: "Khoản thanh toán",
  pickDate: "Chọn ngày",
  exit: "Thoát",
  productCertification: "Chứng nhận sản phẩm",
  dateOfCompanyRegistration: "Ngày thành lập công ty",
  contactPerson: "Người liên hệ",
  contactPersonPhone: "SĐT người liên hệ",
  success: "Thành công!",
  fail: "Thất bại!",
  edit: "Sửa",
  emptyData: "Dữ liệu không tồn tại",
  delete: "Xóa",
  active: "Đang hoạt động",
  inactive: "Ngừng hoạt động",
  deleted: "Đã xóa",
  emptyList: "Danh sách trống/列表为空",
  // --------------------------------------------------------------------
  fromDate: "Từ ngày",
  toDate: "Đến ngày",
  ordered: "Đã đặt hàng",
  transporting: "Đang vận chuyển",
  returnedToPort: "Đã về cảng",
};

const CHINESE = {
  login: "登录",
  logout: "登出",
  forgotPassword: "忘记密码",
  password: "密码",
  confirmPassword: "确认密码",
  resetPassword: "重设密码",
  changePassword: "更改密码",
  numericalOrder: "数值顺序",
  addNew: "添新",
  add: "更多的",
  cancel: "取消",
  save: "救",
  phoneNumber: "电话号码",
  address: "地址",
  createdDate: "创建日期",
  lastUpdatedDate: "Ngày cập nhật cuối",
  supplier: "Nhà cung cấp",
  export: "Export",
  search: "Tìm kiếm",
  delete: "Xóa",
  deleteSearching: "Xóa tìm kiếm",
  creator: "Người tạo",
  updatePerson: "Người cập nhật",
  representative: "Người đại diện",
  construction: "Công trình",
  orderCode: "Mã đơn hàng",
  contractCode: "Mã hợp đồng",
  dueDate: "Thời hạn hoàn công",
  status: "Trạng thái",
  totalMoney: "Tổng tiền",
  vnd: "VNĐ",
  supplierCode: "Mã nhà cung cấp",
  supplierName: "Tên nhà cung cấp",
  email: "Email",
  tax: "Mã số thuế",
  contactAddress: "Địa chỉ liên hệ",
  officeAddress: "Địa chỉ trụ sở",
  fullName: "Họ tên",
  staffName: "Tên nhân viên",
  account: "Tài khoản",
  addAccount: "Thêm tài khoản",
  deleteAccount: "Xóa tài khoản",
  editAccount: "Sửa tài khoản",
  config: "Cấu hình",
  supplier: "Nhà cung cấp",
  addSupplier: "Thêm nhà cung cấp",
  editSupplier: "Sửa nhà cung cấp",
  order: "Đơn hàng",
  orderDetail: "Chi tiết đơn hàng",
  createOrder: "Tạo đơn hàng",
  editOrder: "Sửa đơn hàng",
  complete: "Hoàn thành",
  orderInfo: "Thông tin đơn hàng",
  constructionName: "Tên công trình",
  warrantyPeriod: "Thời hạn bảo hành",
  percentFinePerDay: "Quá hạn phạt mỗi ngày",
  document: "Tài liệu",
  purchaseContent: "Nội dung mua hàng",
  constructType: "Loại công trình",
  productType: "Loại sản phẩm",
  taxMoney: "Số tiền trước thuế",
  import: "Nhập khẩu",
  payment: "Thanh toán",
  paymentDate: "Ngày thanh toán",
  moneyUnit: "Đơn vị tiền",
  year: "Năm",
  paymentMethod: "Phương thức thanh toán",
  paymentClause: "Khoản thanh toán",
  pickDate: "Chọn ngày",
  exit: "Thoát",
  productCertification: "Chứng nhận sản phẩm",
  dateOfCompanyRegistration: "Ngày đăng ký công ty",
  contactPerson: "Người liên hệ",
  contactPersonPhone: "SĐT người liên hệ",
  success: "Thành công!",
  fail: "Thất bại!",
  edit: "Sửa",
  emptyData: "Dữ liệu không tồn tại",
  delete: "Xóa",
  active: "Đang hoạt động",
  inactive: "Ngừng hoạt động",
  deleted: "Đã xóa",
  emptyList: "Danh sách trống",
  // --------------------------------------------------------------------
};

// xin ý kiến nên tách hay không và tách ntn
// Anh Tuấn + Tùng

export { ROUTER, STRING, CHINESE };
